# Generated by Django 2.0 on 2018-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple', models.CharField(max_length=30)),
                ('orange', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
