# Generated by Django 2.0 on 2018-01-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_postsattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='additional2',
            field=models.TextField(default='hello'),
        ),
    ]
